### ISSUE TITLE
Relevant B2C configurations

### ISSUE THREAD

**Issue by abedon** [Azure-Samples/active-directory-b2c-javascript-nodejs-webapi#1]
Hi,

I set up and run this nodejs webapi locally and have it called by the OpenIdConnect-DotNet-Core webapp sample. But unfortunately I always get the "authentication failed due to: token is not found" issue when click the API link. Attached API logs below. I believe this is related to some settings such as keys/scope/App ID URI and etc. 

Would you mind providing details about how to configure the AAD B2C settings for the two applications (both the API and the webapp)?

{"name":"AzureAD: Bearer Strategy","hostname":"STLW10ASDC","pid":21300,"level":30,"msg":"In Strategy.prototype.authenticate: {\"metadataURL\":\"https://login.microsoftonline.com/ttabe.onmicrosoft.com/v2.0/.well-known/openid-configuration/?x-client-SKU=passport-azure-ad&x-client-Ver=3.0.8&p=b2c_1_susi\",\"cacheKey\":\"https://login.microsoftonline.com/ttabe.onmicrosoft.com/v2.0/.well-known/openid-configuration/?x-client-SKU=passport-azure-ad&x-client-Ver=3.0.8&p=b2c_1_susi\"}","time":"2017-08-04T20:01:41.098Z","v":0}

{"name":"AzureAD: Bearer Strategy","hostname":"STLW10ASDC","pid":21300,"level":30,"msg":"In Strategy.prototype.authenticate: received metadata: {\"url\":\"https://login.microsoftonline.com/ttabe.onmicrosoft.com/v2.0/.well-known/openid-configuration/?x-client-SKU=passport-azure-ad&x-client-Ver=3.0.8&p=b2c_1_susi\",\"metadata\":{\"issuer\":\"https://login.microsoftonline.com/ba272794-5cd2-4406-b1c1-c5f2d4553537/v2.0/\",\"authorization_endpoint\":\"https://login.microsoftonline.com/ttabe.onmicrosoft.com/oauth2/v2.0/authorize?p=b2c_1_susi\",\"token_endpoint\":\"https://login.microsoftonline.com/ttabe.onmicrosoft.com/oauth2/v2.0/token?p=b2c_1_susi\",\"end_session_endpoint\":\"https://login.microsoftonline.com/ttabe.onmicrosoft.com/oauth2/v2.0/logout?p=b2c_1_susi\",\"jwks_uri\":\"https://login.microsoftonline.com/ttabe.onmicrosoft.com/discovery/v2.0/keys?p=b2c_1_susi\",\"response_modes_supported\":[\"query\",\"fragment\",\"form_post\"],\"response_types_supported\":[\"code\",\"id_token\",\"code id_token\"],\"scopes_supported\":[\"openid\"],\"subject_types_supported\":[\"pairwise\"],\"id_token_signing_alg_values_supported\":[\"RS256\"],\"token_endpoint_auth_methods_supported\":[\"client_secret_post\"],\"claims_supported\":[\"oid\",\"sub\",\"newUser\",\"postalCode\",\"name\",\"idp\",\"tfp\"]},\"authtype\":\"oidc\",\"oidc\":{\"algorithms\":[\"RS256\"],\"authorization_endpoint\":\"https://login.microsoftonline.com/ttabe.onmicrosoft.com/oauth2/v2.0/authorize?p=b2c_1_susi\",\"end_session_endpoint\":\"https://login.microsoftonline.com/ttabe.onmicrosoft.com/oauth2/v2.0/logout?p=b2c_1_susi\",\"issuer\":\"https://login.microsoftonline.com/ba272794-5cd2-4406-b1c1-c5f2d4553537/v2.0/\",\"token_endpoint\":\"https://login.microsoftonline.com/ttabe.onmicrosoft.com/oauth2/v2.0/token?p=b2c_1_susi\",\"keys\":[{\"kid\":\"X5eXk4xyojNFum1kl2Ytv8dlNP4-c57dO6QGTVBwaNk\",\"nbf\":1493763266,\"use\":\"sig\",\"kty\":\"RSA\",\"e\":\"AQAB\",\"n\":\"tVKUtcx_n9rt5afY_2WFNvU6PlFMggCatsZ3l4RjKxH0jgdLq6CScb0P3ZGXYbPzXvmmLiWZizpb-h0qup5jznOvOr-Dhw9908584BSgC83YacjWNqEK3urxhyE2jWjwRm2N95WGgb5mzE5XmZIvkvyXnn7X8dvgFPF5QwIngGsDG8LyHuJWlaDhr_EPLMW4wHvH0zZCuRMARIJmmqiMy3VD4ftq4nS5s8vJL0pVSrkuNojtokp84AtkADCDU_BUhrc2sIgfnvZ03koCQRoZmWiHu86SuJZYkDFstVTVSR0hiXudFlfQ2rOhPlpObmku68lXw-7V-P7jwrQRFfQVXw\"}]}}","time":"2017-08-04T20:01:41.100Z","v":0}
{"name":"AzureAD: Bearer Strategy","hostname":"STLW10ASDC","pid":21300,"level":30,"msg":"In Strategy.prototype.authenticate: we will validate the following options: [object Object]","time":"2017-08-04T20:01:41.101Z","v":0}

{"name":"AzureAD: Bearer Strategy","hostname":"STLW10ASDC","pid":21300,"level":30,"msg":"authentication failed due to: token is not found","time":"2017-08-04T20:01:41.102Z","v":0}
GET /hello 401 5.397 ms - -

**Comment by lovemaths** [comment]
@abedon  Can you open Fiddler when you send the request to nodejs api, and check if token is provided in the request?  The request should look like this:

```
Get /hello

Header:
Authorization: Bearer the_access_token                 <===== check this part in your request
```

**Comment by abedon** [comment]
@lovemaths, it's working now, figured out I should use scope value instead of names in the request. Also, made some changes to the scope and API access settings. My feeling is the current documents about end-to-end B2C configurations are not detailed enough and some contents are confusing.

**Comment by jamie-digital** [comment]
@abedon how did you fix it? I'm encountering the same problem.

**Comment by abedon** [comment]
Understood, the document sucks. 

Here's what I did (assuming all sign in/up policies are set up):
1. Register your nodejs webapi in ADB2C, configure the followings:
    - include web app/api: yes
    - set reply url to "http://localhost:5000" 
    - set app id uri to "nodejsapi"
    - add a scope "read" with any description
2. Register your calling app (whatever is going to call the nodejs webapi) , in my case I'm using [HelloJSApp](https://github.com/Azure-Samples/active-directory-b2c-javascript-hellojs-singlepageapp), configure the followings:
    - include web app/api: yes
    - set reply url to "http://localhost:65328/redirect.html"
    - add an api access, select the nodejs configured above as the API, and select all scopes
3. Update the code for nodejs and hellojs respectively with the corresponding tenant id, app id (client id), reply url, policies and etc.
4. Set scope in hellojs app code (index.html) to "https://[your tenant id]/nodejsapi/read"
5. You probably need to modify the nodejsapi code in order to parse the scope value properly:
`if (claims['scp'].split(" ").indexOf("read") >= 0) {`

That's all. Let me know if it works.

**Comment by jamie-digital** [comment]
That worked great, thanks :)

**Comment by derisen** [comment]
The issue seems resolved. Closing this.
