### ISSUE TITLE
Cannot verify token

### ISSUE THREAD

**Issue by leonbrag** [Azure-Samples/active-directory-b2c-javascript-nodejs-webapi#11]
If validateIssuer set to true, following error is reported: 
authentication failed due to: jwt issuer is invalid

What needs to happen to verify issuer?

**Comment by jennyf19** [comment]
@leonbrag if you're using b2c, you have to set validate issuer to false because the authority is not an AAD authority. The middleware (passport) is validating the token against a list of known authorities, so in this case, for b2c, you need to set it to false, otherwise you will get this error.

**Comment by leonbrag** [comment]
I got it to work with b2c and validate issuer set to true. I had to set correct end point, but it worked.
