### ISSUE TITLE
Sorry, but... Does this project have an ASP.NET Core alternative?

### ISSUE THREAD

**Issue by Anduin2017** [Azure-Samples/active-directory-b2c-javascript-nodejs-webapi#12]
Sorry, but... Does this project have an ASP.NET Core alternative?

I come from this repo: https://github.com/Azure-Samples/active-directory-b2c-xamarin-native

And I am a .NET developer. This project runs fine and I can successfully connect my API.

But, I really need a C# version of it. So is there?

**Comment by jmprieur** [comment]
@Anduin2017 : https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2 is a multi-step ASP.NET Core Web app tutorial.
One of the steps is B2C: https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/1-WebApp-OIDC/1-5-B2C

We are working on the Web API aspect: https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/pull/192

Meanwhile you can also have a look at https://github.com/Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi

**Comment by Anduin2017** [comment]
Hi, thanks for your response!

I found the alternative: 

https://github.com/azure-samples/active-directory-b2c-dotnetcore-webapi

Thank you again!
