### ISSUE TITLE
crashes if no scp claim passed

### ISSUE THREAD

**Issue by cljung** [Azure-Samples/active-directory-b2c-javascript-nodejs-webapi#13]
If you pass a token with no 'scp' claim, the app crashes with error
<code>TypeError: Cannot read property 'split' of undefined</code>

index.js row #54 should be
<code>if ( 'scp' in claims && claims['scp'].split(" ").indexOf("demo.read") >= 0) {</code>

**Comment by jennyf19** [comment]
@cljung feel free to propose a PR

**Comment by derisen** [comment]
This change has been incorporated in the [PR](https://github.com/Azure-Samples/active-directory-b2c-javascript-nodejs-webapi/pull/16). Closing this.
