### ISSUE TITLE
Clone the code references incorrect repo

### ISSUE THREAD

**Issue by petertuton** [Azure-Samples/active-directory-b2c-javascript-nodejs-webapi#17]
The "Clone the code" step in README.md references the incorrect repo.

Reference is to: https://github.com/Azure-Samples/active-directory-javascript-nodejs-webapi-v2 whereas it should reference: https://github.com/Azure-Samples/active-directory-b2c-javascript-nodejs-webapi 

`git clone https://github.com/Azure-Samples/active-directory-b2c-javascript-nodejs-webapi`

**Comment by derisen** [comment]
great catch @petertuton ! fixing now
