### ISSUE TITLE
No user info data

### ISSUE THREAD

**Issue by marcosvidolin** [Azure-Samples/active-directory-b2c-javascript-nodejs-webapi#21]
Hi,

I got no error using the API and it is responding and logging the "Validated clams" information, but I have no user information in "req.user" attribute.
What can I configure to get the response?

Thank you

**Comment by derisen** [comment]
@marcosvidolin sorry this went unattended. So the `req.user` attribute is usually populated with session information about an authenticated user, but sessions are not common/appropriate for web API's, as API servers typically require credentials to be supplied with each request. As such, our sample is not covering this. 

If you have some custom logic for populating `req.user` after an authorized call, you could do so at line 18 in `index.js`:

```javascript
const bearerStrategy = new BearerStrategy(config,
    function (token, done) {
        // Send user info using the second argument
        done(null, { /* USER INFO */ }, token);
    }
);
```

But for sessions you should take a look at a web app sample. You can see some such samples [here](https://github.com/AzureAD/passport-azure-ad#7-samples-and-documentation). 

Let me know if you need anything further.

**Comment by marcosvidolin** [comment]
Thank you @derisen 
That's all
