### ISSUE TITLE
Add Screenshots Of The Relevant B2C Config To The README

### ISSUE THREAD

**Issue by opticyclic** [Azure-Samples/active-directory-b2c-javascript-nodejs-webapi#24]
The README has links to 3 separate tutorials in order to configure this for yourself then it says to configure variables in the config.js based on those 3 tutorials.

Each tutorial is quite long and has lots of steps.

It would make things a lot clearer if you added screenshots of the Azure portal used in this demo for each of the 4 variables so there is something to compare against to make sure the right values are in the config file and are taken from the right place in the portal.

UPDATE:
The most useful screenshot would be of the Run Userflow https://docs.microsoft.com/en-ca/azure/active-directory-b2c/media/tutorial-create-user-flows/signup-signin-run-now.png

The part that says "Run user flow endpoint" has a url below it.
This is the url that the config.js is creating with those variables

```
const config = {
    identityMetadata: "https://" + b2cDomainHost + "/" + tenantId + "/" + policyName + "/v2.0/.well-known/openid-configuration/",
    clientID: clientID,
    policyName: policyName,
...
...
```
Highlighting this would be the easiest way for people to check that they have modified the sample correctly.

**Comment by derisen** [comment]
@opticyclic this is a good suggestion. Would you like to make a PR for it?
