### ISSUE TITLE
Broken README link for the frontend example

### ISSUE THREAD

**Issue by carneirofc** [Azure-Samples/active-directory-b2c-javascript-nodejs-webapi#28]
### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] question
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```
The README.md link [JavaScript Single-page Application calling a custom Web API with MSAL.js 2.x using the auth code flow with PKCE](https://github.com/Azure-Samples/ms-identity-javascript-callapi) is broken.

[L34 Overview section of README.md](https://github.com/Azure-Samples/active-directory-b2c-javascript-nodejs-webapi/blob/master/README.md)

Maybe it's supposed to be [this](https://github.com/Azure-Samples/ms-identity-b2c-javascript-spa) repo?

### Minimal steps to reproduce
> Acess https://github.com/Azure-Samples/ms-identity-javascript-callapi

**Comment by derisen** [comment]
@carneirofc thank you so much for catching this. You are right, [that](https://github.com/Azure-Samples/ms-identity-b2c-javascript-spa) was the repo intended. Will make a PR asap (you're welcome to do it as well).

**Comment by carneirofc** [comment]
Thank you for your feedback! I've opened a [pull request](https://github.com/Azure-Samples/active-directory-b2c-javascript-nodejs-webapi/pull/29) with the new link.
