### ISSUE TITLE
outdated readme.md on Token validation section

### ISSUE THREAD

**Issue by Gnol-VN** [Azure-Samples/active-directory-b2c-javascript-nodejs-webapi#30]
In this section [https://github.com/Azure-Samples/active-directory-b2c-javascript-nodejs-webapi#token-validation](url)
 ```
app.get('/api', passport.authenticate('oauth-bearer', { session: false }),
        (req, res) => {
            console.log('Validated claims: ', req.authInfo);
    );
````
`/api` should be replaced by `/hello`, as shown in `index.js`

**Comment by derisen** [comment]
@Gnol-VN thanks a lot for catching this! Feel free to propose a PR for correction I'll review (if not, I'll correct it soon).
